apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pale-2-register
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  gcp:
    sqlInstances:
      - name: pale-2-register-instance
        type: POSTGRES_14
        diskSize: 100
        databases:
          - name: pale-2-register
            envVarPrefix: DB
            users:
              - name: macgyver
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
        tier: db-custom-1-3840
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 15m
      memory: 512Mi
  filesFrom:
    - secret: pale2-google-creds
  kafka:
    pool: nav-prod
  envFrom:
    - secret: pale-2-secret
