apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pale-2-register
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvpale2reg
        mountPath: /secrets/serviceuser
      - kvPath: /kv/prod/fss/pale-2-register/teamsykmelding
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  kafka:
    pool: nav-prod
  ingresses:
    - "https://pale-2-register.nais.adeo.no"
  env:
    - name: PALE_2_REGISTER_DB_URL
      value: jdbc:postgresql://A01DBVL011.adeo.no:5432/pale-2-register
    - name: MOUNT_PATH_VAULT
      value: /postgresql/prod-fss
    - name: PALE_BUCKET_NAME
      value: teamsykmelding-pale2-legeerklaring-bucket-prod