apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pale-2-register
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvpale2reg
        mountPath: /secrets/serviceuser
      - kvPath: /kv/preprod/fss/pale-2-register/default
        mountPath: /secrets/default
  ingresses:
    - "https://pale-2-register.nais.preprod.local"
  env:
    - name: PALE_2_REGISTER_DB_URL
      value: jdbc:postgresql://b27dbvl013.preprod.local:5432/pale-2-register
    - name: SERVICE_USER_USERNAME
      value: /secrets/serviceuser/username
    - name: SERVICE_USER_PASSWORD
      value: /secrets/serviceuser/password
    - name: MOUNT_PATH_VAULT
      value: /postgresql/preprod-fss
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
